module.exports = [
    'BYU-Idaho (id: 1)',
    '\tOnline (id: 5)',
    '\t\tMaster Courses (id: 42)',
    '\t\t\tCourse Council (id: 46)',
    '\t\t\tFile Backup (id: 100)',
    '\t\tSemeseter Blueprint (id: 43)',
    '\t\t\tScaled (id: 44)',
    '\t\t\tArchived (id: 45)',
    '\tCampus (id: 7)',
    '\t\tCampus Instructor Training (id: 35)',
    '\tSandbox (id: 8)',
    '\tDevelopment (id: 13)',
    '\t\tCanvas API test (id: 17)',
    '\t\tWorkday Tests (id: 18)',
    '\t\tConversion Tool (id: 19)',
    '\t\tCanvas Gauntlets (id: 27)',
    '\t\tEnglishConnect (id: 41)',
    '\t\tSub-Account Testing (id: 112)',
    '\t\tWhite Glove Migration Courses (id: 114)',
    '\t\tCourse Removal Testing (id: 120)',
    '\tPathway (id: 24)',
    '\t\tMaster Courses (id: 39)',
    '\t\t\tCourse Council (id: 47)',
    '\t\t\tFile Backup (id: 102)',
    '\t\tSemester Blueprint (id: 106)',
    '\t\t\tArchived (id: 108)',
    '\t\t\tScaled (id: 110)',
    '\t\t\tMissionary Review Courses (id: 118)',
    '\tNon-Academic (id: 25)',
    '\t\tDevotional (id: 96)',
    '\t\tHuman Resources (id: 98)',
    '\t\tOnline Instruction (id: 104)',
    '\tManually Created Courses (id: 26)',
    '\tBYUI (id: 48)',
    '\t\tAccounting (id: 49)',
    '\t\tEconomics (id: 50)',
    '\t\tApplied Plant Science (id: 51)',
    '\t\tSociology & Social Work (id: 52)',
    '\t\tDesign & Const Mgmt (id: 53)',
    '\t\tArt (id: 54)',
    '\t\tAnimal & Food Science (id: 55)',
    '\t\tEngineering Technology (id: 56)',
    '\t\tManagement (id: 57)',
    '\t\tMarketing (id: 58)',
    '\t\tFinance (id: 59)',
    '\t\tBiology (id: 60)',
    '\t\tMechanical & Civil Eng (id: 61)',
    '\t\tChemistry (id: 62)',
    '\t\tHome & Family (id: 63)',
    '\t\tLang & Intnl Studies (id: 64)',
    '\t\tComputer Info Technology (id: 65)',
    '\t\tCommunication (id: 66)',
    '\t\tComputer Sci & Eng (id: 67)',
    '\t\tTheatre and Dance (id: 68)',
    '\t\tTeacher Education (id: 69)',
    '\t\tEnglish (id: 70)',
    '\t\tHuman Performance & Rec (id: 71)',
    '\t\tFoundations (id: 72)',
    '\t\tMathematics (id: 73)',
    '\t\tReligious Education (id: 74)',
    '\t\tInterdiscip. Studies (id: 75)',
    '\t\tHist Geog & Polisci (id: 76)',
    '\t\tGeology (id: 77)',
    '\t\tHumanities & Philosophy (id: 78)',
    '\t\tGeneral Studies (id: 79)',
    '\t\tHealth Services (id: 80)',
    '\t\tLiberary (id: 81)',
    '\t\tROTC (id: 82)',
    '\t\tMusic (id: 83)',
    '\t\tNursing (id: 84)',
    '\t\tPhysics (id: 85)',
    '\t\tPsychology (id: 86)'
]